[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/tecnicas/*"
  to = "/tecnicas/:splat.html"
  status = 200

[[redirects]]
  from = "/recetas/*"
  to = "/recetas/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404